// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCebbkD3-NtxIJV7NE78fQwWcbHsaBBACI',
    appId: '1:914422888140:web:cfb18c3a22c753996f7469',
    messagingSenderId: '914422888140',
    projectId: 'dermaafrica-b2cd9',
    authDomain: 'dermaafrica-b2cd9.firebaseapp.com',
    storageBucket: 'dermaafrica-b2cd9.firebasestorage.app',
    measurementId: 'G-F1X2TGWKH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ6ncWO-kG1ud1XiQlt6TkFOQ3ZMwLDds',
    appId: '1:914422888140:android:a649eaecf032a0646f7469',
    messagingSenderId: '914422888140',
    projectId: 'dermaafrica-b2cd9',
    storageBucket: 'dermaafrica-b2cd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdAQKz4RyR1AvgDkWm-_DqJOVE3uQxKFs',
    appId: '1:914422888140:ios:f8652aabad0bbc466f7469',
    messagingSenderId: '914422888140',
    projectId: 'dermaafrica-b2cd9',
    storageBucket: 'dermaafrica-b2cd9.firebasestorage.app',
    iosBundleId: 'com.example.dermatriage',
  );
}
